name: Test

on:
  push:
    branches: [main]
    paths:
      - 'src/**/*.ts'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'tsconfig.build.json'
      - '.github/workflows/test.yml'
      - '.github/workflows/_node-ci-bootstrap.yml'
  pull_request:
    branches: [main]
    paths:
      - 'src/**/*.ts'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'tsconfig.build.json'
      - '.github/workflows/test.yml'
      - '.github/workflows/_node-ci-bootstrap.yml'

jobs:
  install:
    uses: ./.github/workflows/_node-ci-bootstrap.yml
    with:
      node-version: '20'

  test:
    needs: install
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm run test
